version: 2
updates:
- package-ecosystem: gitsubmodule
  directory: "/."
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  reviewers:
  - khodand
  
  - package-ecosystem: gitsubmodule
  directory: "/."
  schedule:
    interval: daily
    time: "9:00"
  open-pull-requests-limit: 10
  target-branch: "junior"
  labels:
  - "junior"
  reviewers:
  - khodand
